Output progressbar.gif
Set FontSize 20
Set FontFamily  "JetBrains Mono"
Set Shell zsh
Set TypingSpeed 0.08
Sleep 500ms
Type "python"
Enter
Sleep 250ms
Type "import progressbar"
Enter
Sleep 250ms
Type "import time"
Enter
Sleep 500ms
Type "progress = progressbar.ProgressBar()"
Enter
Sleep 500ms
Type "for i in progress(range(100)):"
Enter
Sleep 500ms
Type "time.sleep(0.05)"
Enter 2
Sleep 7s
Ctrl+D
Ctrl+D

